baseurl: 'https://username.github.io'
DefaultContentLanguage: en
title: Galactic Goats
theme: beautifulhugo
pygmentsStyle: trac
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
Params:
  subtitle: We are everywhere
  mainSections:
    - post
    - posts
  logo: img/goat.png
  favicon: img/favicon.ico
  dateFormat: 'January 2, 2006'
  commit: false
  rss: true
  comments: true
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true
Author:
  name: Mr.Goat
  # website: yourwebsite.com
  email: youremail@domain.com
  github: username
  # facebook: username
  # bitbucket: username
  # gitlab: username
  # twitter: username
  # reddit: username
  # linkedin: username
  # xing: username
  # stackoverflow: users/XXXXXXX/username
  # snapchat: username
  # instagram: username
  # youtube: user/username
  # soundcloud: username
  # spotify: username
  # bandcamp: username
  # itchio: username
  # vk: username
  # paypal: username
  # telegram: username
  # 500px: username
  # codepen: username
  # mastodon: url
  # kaggle: username
  # weibo: username
  # slack: username
  # medium: username
  # strava: userid
  # discord: 'invite code (https://discord.gg/XXXXXXX)'


menu:
  main:
    - name: API
      url: 'page/api/'
      weight: 1

    - name: About
      url: page/about/
      weight: 3

    # - name: Blog
    #   url: ''
    #   weight: 1

    # - identifier: samples
    #   name: Samples
    #   weight: 2
    # - parent: samples
    #   name: Big Image Sample
    #   url: post/2017-03-07-bigimg-sample
    #   weight: 1
    # - parent: samples
    #   name: Math Sample
    #   url: post/2017-03-05-math-sample
    #   weight: 2
    # - parent: samples
    #   name: Code Sample
    #   url: post/2016-03-08-code-sample
    #   weight: 3
